### ISSUE TITLE
[BUG] Permission ".*" not working properly

### ISSUE THREAD

**Issue by miniSpoXster777** [Exiled-Team/DiscordIntegration#106]
**Describe the bug**
To be able to use commands by the bot, they must be added separately in the DiscordIntegration-config.json configuration. Otherwise, granting the permission ".*" to role does not work because the bot returns "That command is not enabled on this server."

**To Reproduce**
1. Go to 'DiscordIntegration-config.json'
2. Change role permission to ".*"
3. Restart bot
4. Try command example "/send 1 ban" > bot will return Code 6
5. Back to 'DiscordIntegration-config.json'
6. Replace ".*" with "ban"
7. Restart bot
8. Try command againg "/send 1 ban" > bot will return this: https://cdn.discordapp.com/attachments/987254233638252574/987632885672607774/unknown.png

**Expected behavior**
Bot should not return code 6 but https://cdn.discordapp.com/attachments/987254233638252574/987632885672607774/unknown.png

**Server logs**
none

**EXILED Version ("latest" is not a version):**
5.2.1

**Results of `show plugins` command in console:**
https://pastebin.com/nufFpcDB

**Additional context**
none

**Comment by miniSpoXster777** [comment]
> Hi! I wanna add that command unban not works either giving command to role _unban, unban id or unban ip_ Giving same error as above with .* ![image](https://github.com/assets/94808550/c4c19dc2-90cb-4f70-9252-755536b911ec) ![image](https://github.com/assets/94808550/331d53dc-e8a6-49f1-936b-8c93961a146c) ![image](https://github.com/assets/94808550/0525625d-b7e4-4e1f-a305-c5a45f8ca1e9)

Try not to use spaces in command names. Instead of "di playerslist", "di stafflist", "di reload" try to use only "di" and also with unban try use ony "unban" not "unban id" and "unban ip". It should be working

**Comment by joker-119** [comment]
Spaces or not, work fine.
It seems I forgot to add handling the `.*` permission string properly, will fix in an update soon.
