### ISSUE TITLE
[BUG] Keeps repeating same log

### ISSUE THREAD

**Issue by Zenlet** [Exiled-Team/DiscordIntegration#107]
**Describe the bug**
The bot does not move onto the next message, it keeps reposting the same message over and over until it is restarted.

**To Reproduce**
1. have a bot
2. kill lots of people ingame so damage logs appear
3. look at discord
4. see

**Expected behavior**
for the bot to move onto the next log message, ie user joined the server

**EXILED Version ("latest" is not a version):**
5.1.1

**Additional context**
i think it may only happen with messages that reach the character limit

**Comment by Zenlet** [comment]
i set hurting_player to false and it doesn't get stuck anymore.

**Comment by jake-baxter** [comment]
Also seems like its happening on intercom events as well

**Comment by Zenlet** [comment]
It only happens when the message gets full

**Comment by ExPort-Gaming** [comment]
For me it happens on `hurt_player`, `player_triggering_tesla` and `player_intercom_speaking`. It keeps getting me temp-IP banned off Discord for 1 hour and it's annoying. Yes, I have disabled the `events_to_log` events that are causing the issue but sometimes it repeats older logs when the bot restarts or the configs change back.
