### ISSUE TITLE
[BUG] Bot doesn't work after server restart

### ISSUE THREAD

**Issue by Raul125** [Exiled-Team/DiscordIntegration#121]
**Describe the bug**
The bots work normally, but when the server restarts, you need to restart the bot to re-establish the connection with the server.

**To Reproduce**
1. Start your scp server and then the bot
2. All is working fine now
3. Restart your server
4. The connection with the server and the bot is broken

**Expected behavior**
To not close the connection.

**Server logs**
There's nothing, the bot console stop showing the "CreateBasic Sending embed" log. 
After you restart the bot to fix the problem, the server show this [Console Log](https://gyazo.com/4eb7cd889fe10f19793c99d52b232c9a) and then it works fine again.

**EXILED Version ("latest" is not a version):**
5.3.0 beta 4

**Comment by Nathan43615** [comment]
Exact same bug for me, also running on 5.3.0 beta 4

Specifically when restarting the server using softrestart
