### ISSUE TITLE
[BUG] Plugin.tar.gz folder structure issue

### ISSUE THREAD

**Issue by EsserGaming** [Exiled-Team/DiscordIntegration#127]
On the latest version of DI (6.0.4-1.5.0) the plugin tar.gz file extract as the way it should. As it does this:

`Plugin.tar.gz -> Plugin -> dependencies and then DiscordIntegration.dll`
And it used to not have the Plugin folder (which screws up many things, especially for pre-made eggs)

**Comment by joker-119** [comment]
Fixed
