### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Dev-prizrakk** [Exiled-Team/DiscordIntegration#130]
Hello, will it be fixed?
(I use all the latest)
![изображение](https://user-images.githubusercontent.com/88229427/190457752-e48bcd40-52ee-4482-8e0b-37a39166c63c.png)

**Comment by Dev-prizrakk** [comment]
If anything, I'm talking about the unit at the beginning of the team

**Comment by joker-119** [comment]
I have absolutely no idea whatsoever what you are trying to refer to here.

**Comment by Dev-prizrakk** [comment]
I'm talking about 1 at the beginning of the embed header
