### ISSUE TITLE
[BUG] Generator Activated Log Error

### ISSUE THREAD

**Issue by xNexus-ACS** [Exiled-Team/DiscordIntegration#132]
![image](https://user-images.githubusercontent.com/83370388/196307627-7ef49364-c962-49a8-8820-ede6708c8314.png)

As you can see joker in the image, it's seems it's a little bit bugged the Generator Activated Log

EXILED VERSION: 5.3.1
DiscordIntegration VERSION: LATEST

**Comment by joker-119** [comment]
1. "Latest" is not a version. Please always include the version numbers when making bug reports.
2. This is an exiled bug with Map.Room.ToString(), please report the bug on the EXILED github.

**Comment by xNexus-ACS** [comment]
Ok 😉
