### ISSUE TITLE
[BUG] PlayerJoin

### ISSUE THREAD

**Issue by BenFRC5147** [Exiled-Team/DiscordIntegration#141]
**Describe the bug**
Player join is not logged

**To Reproduce**
Enable player join to be logged in Configs
Have a player join
See that the Join is not logged ( at least in text, I didn't check embed)

**Expected behavior**
Player join is logged <3

**Server logs**
[LocalAdmin Log 2023-03-07 19.10.56.txt](https://github.com/Exiled-Team/DiscordIntegration/files/10913186/LocalAdmin.Log.2023-03-07.19.10.56.txt)

**EXILED Version ("latest" is not a version):**
beta 26

**Results of `show plugins` command in console:**
![image](https://user-images.githubusercontent.com/13715542/223528204-f07f5c9b-9a64-4ba1-8679-2c4820dc7ac8.png)
![image](https://user-images.githubusercontent.com/13715542/223528272-72ae74a5-1ddf-48e9-8952-452744de8f68.png)
![image](https://user-images.githubusercontent.com/13715542/223528369-56258e92-6679-455b-8e5d-93a1367a3c8f.png)
![image](https://user-images.githubusercontent.com/13715542/223528406-efc866b7-7675-4f7b-bc5a-74a180bbdcd3.png)

**Additional context**

**Comment by joker-119** [comment]
As indicated in the error message, you do not have the LiteDB.dll dependency installed

**Comment by BenFRC5147** [comment]
Oh, okay. That wasn't included in the .tar.gz file I got from the release, where can I find that?

**Comment by joker-119** [comment]
Oh, odd it should have been. Check the previous few releases, if it's not in any of them i will need to update the release files later this afternoon.

**Comment by joker-119** [comment]
It was a recent addition, glad to hear you got one, I'll fix the release to have it for the future
