### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Logic-Gun** [Exiled-Team/DiscordIntegration#142]
**Describe the bug**

**To Reproduce**
1. Start DiscordIntegration & SCP:SL Server and settings 

**Expected behavior**
Logs don`t duplicated.

**Server logs**
-

**EXILED Version ("latest" is not a version):** latest

**Results of `show plugins` command in console:** clear plugins

**Additional context**
Logs duplicated.

**Comment by Logic-Gun** [comment]
Logs in discord*

**Comment by joker-119** [comment]
Don't setup the normal logs and the staff copy logs to the same channel, and you won't have duplicate logs. Also gj not filling out most of the bug report form.
