### ISSUE TITLE
please log player id

### ISSUE THREAD

**Issue by GoldenPig1205** [Exiled-Team/DiscordIntegration#146]
Please edit the player ID so that it is also recorded. I really need that feature.

**Comment by GoldenPig1205** [comment]
and escape log

**Comment by lucasgames8957** [comment]
We shouldn't do the UUID as it is editable and for security reason but is it ok with it being just the player name instead?

If you want it can be a configurable option to where the UUID goes in a private channel while player name is in the public channel (if you are going to use two channels)

**Comment by GoldenPig1205** [comment]
I just wanted to use player id on di, what do you mean?

**Comment by joker-119** [comment]
tf are you even talking about lucas? What do you mean by UUID?

**Comment by lucasgames8957** [comment]
> tf are you even talking about lucas? What do you mean by UUID?

UUID: "Unique User ID"

**Comment by GoldenPig1205** [comment]
yes
