### ISSUE TITLE
[BUG] Discord bot displays number of players incorrectly

### ISSUE THREAD

**Issue by Tamago4a** [Exiled-Team/DiscordIntegration#151]
**Describe the bug:**
Discord bot displays player count incorrectly. It counts NPCs when it shouldn't.

**To Reproduce:**
1. Add plugin and configure bot
2. Create NPC on server
3. Make sure the number of players displayed is incorrect

**EXILED Version:**
8.11.0

**Comment by joker-119** [comment]
This, if anything, is a bug in EXILED, and should be reported to them. It uses Player.List and that list should not contain NPCs.

This could be adjusted in the plugin, but I don't care enough to do so, willing to accept a PR for this.

**Comment by Tamago4a** [comment]
Got it. I thought it was your mistake. Okay, I'll make a bug report to exiled.

**Comment by Tamago4a** [comment]
Although I don't quite understand. Why then is the number of players in the server list displayed correctly?

**Comment by Tamago4a** [comment]
#153
