### ISSUE TITLE
[Feature]Separate channel for reports

### ISSUE THREAD

**Issue by 4310V343k** [Exiled-Team/DiscordIntegration#39]
Title related
Separate config option for [LocalReporting](https://github.com/Exiled-Team/EXILED/blob/master/Exiled.Events/EventArgs/LocalReportingEventArgs.cs) and [ReportingCheater](https://github.com/Exiled-Team/EXILED/blob/master/Exiled.Events/EventArgs/ReportingCheaterEventArgs.cs) events

**Comment by iopietro** [comment]
I'll do it tomorrow
