### ISSUE TITLE
[Enhancement]Inline codeblocks for names

### ISSUE THREAD

**Issue by 4310V343k** [Exiled-Team/DiscordIntegration#41]
Because of the *s and _s in some nicknames discord tries to highlight logs in **bold** and *cursive*

One way to solve it is to wrap EVERY message in multiline code block and remove every ` from the arguments

However wrapping just the nicknames into inline codeblocks and removing every ` looks much more cleaner

**Comment by iopietro** [comment]
I was thinking about that, but multi-line messages would broke.
