### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by Turbinator-JP** [Exiled-Team/DiscordIntegration#44]
I have two servers that run off the exiled hosting system, one of the bots works fine, the other doesn't. I have changed the configs to match the port and have the IP as the Localhost '127.0.0.1' however I keep experiencing this error:
'[2021-03-15 02:11:12.823 +00:00] [WARN] [DiscordIntegration] [NET] Connecting to 127.0.0.1:7054.
[2021-03-15 02:11:13.797 +00:00] [ERROR] [DiscordIntegration] [NET] An error has occurred while connecting: Connection refused'
Want to know if this is something in the Bots code or configs that can be causing this or is this a server-side issue that I have to get in contact with the exiled hosting team to rectify.

**Comment by galaxy119** [comment]
Contact Exiled Hosting customer support.
