### ISSUE TITLE
[Error]Bot launch error

### ISSUE THREAD

**Issue by MrAfitol** [Exiled-Team/DiscordIntegration#45]
**When I write "npm install" to the console, it gives me errors**
Screenshot of the error: [Click](https://ibb.co/420fLHd)
**And also when I run the bot "node discordIntegration.js"**
Screenshot of the error: [Click](https://ibb.co/zRFSRJP)

**Comment by iopietro** [comment]
Are you using the latest version of DiscordIntegration (3.1.1)? Are both `package.json` and `discordIntegration.js` inside the same folder? Have you followed every needed step on the readme?

**Comment by MrAfitol** [comment]
> Are you using the latest version of DiscordIntegration (3.1.1)? Are both `package.json` and `discordIntegration.js` inside the same folder? Have you followed every needed step on the readme?

Yes

**Comment by iopietro** [comment]
Are you doing `npm install` in the same folder of `discordIntegration.js` and `package.json`?

**Comment by MrAfitol** [comment]
> Are you using a VPN? Are you running the bot from your PC or a VPS/Dedicated Server?

No, I don't use a VPN, I run a bot from my PC

**Comment by MrAfitol** [comment]
**I solved the problem**

**Comment by iopietro** [comment]
Ok, could you explain how did you solve it for people with the same issue?

**Comment by MrAfitol** [comment]
The problem was that I forgot to add the bot to the server)))

**Comment by iopietro** [comment]
Ok, thanks.
