### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by YakuzaXDev** [Exiled-Team/DiscordIntegration#47]
*[WARN] [DiscordIntegration] [NET] Connecting to MYIP:PORT**
[ERROR] [DiscordIntegration] [NET] An error occurred connecting: Unable to establish a connection as the target computer expressly denied that connection.

**Comment by joker-119** [comment]
You need to make sure the machine running the bot has that port opened on it's firewall, and if that computer is behind a router, it also needs to have the port opened and routed/forwarded correctly.
