### ISSUE TITLE
Is it possible to have a 24-clock time in the logs?

### ISSUE THREAD

**Issue by Oyplap** [Exiled-Team/DiscordIntegration#49]
Hello,

like the title says, is it possible to have an option to have a 24-clock time in the logs? Would be really helpful for people that are used to that kind of time.

Kind regards,
Oyplap

**Comment by untuned** [comment]
This could easily be implemented if timestamps used the Discord native function.
https://discord.com/developers/docs/reference#message-formatting-timestamp-styles
