### ISSUE TITLE
Duplicating log messages

### ISSUE THREAD

**Issue by ITeMbI4** [Exiled-Team/DiscordIntegration#52]
![image](https://user-images.githubusercontent.com/46756889/127558096-0d116a42-a910-4033-aa98-9e9e9c145121.png)

**Comment by ITeMbI4** [comment]
First message is ban with SteamId and second is with IP.

**Comment by ITeMbI4** [comment]
Also these
![image](https://user-images.githubusercontent.com/46756889/127558345-fcf54659-cc26-4df2-acfe-25fa84abf91c.png)

**Comment by ITeMbI4** [comment]
![image](https://user-images.githubusercontent.com/46756889/127558395-278a4bfa-b57e-4f51-a827-676ba7fa1d74.png)

**Comment by iopietro** [comment]
It's game/Exiled fault, not related to DiscordIntegration
