### ISSUE TITLE
Decontamination log spam

### ISSUE THREAD

**Issue by Zenlet** [Exiled-Team/DiscordIntegration#55]
Light containment decontamination started and the bot then spammed the logs with the message "Deconamination has begun."
![qaULLKwRBz](https://user-images.githubusercontent.com/62112167/130356187-1beea9a4-512e-4f04-9c59-c2493bf9e4fb.png)
-

**Comment by joker-119** [comment]
Is this still occuring currently?

**Comment by Zenlet** [comment]
seems to be working now, thanks.

**Comment by joker-119** [comment]
This is being casued by a base-game error in the decon method, exiled I believe has patched the bug, but if not, report it there as "LCS Decon method errors and gets re-called every frame"
