### ISSUE TITLE
[SUGGESTION] Add client console command logging back

### ISSUE THREAD

**Issue by growled** [Exiled-Team/DiscordIntegration#65]
Ever since a recent release of discord integration came out, client console logging through the RA command logs channel has been stopped logging. For us, we'd find it really beneficial to get client console logging back to see who's entering which commands as we have a custom plugin which is currently still quite buggy and we're trying to find out whether someone has initiated something or not which is quite hard without these logs.

I'm not sure whether removing these were intentional or not. If they weren't: is there a possibility of adding it back? If they were: is there a possibility of adding a bool to the config to set whether they show up or not?

Many thanks. I'm sorry if this isn't the right place to post this, I couldn't think of anywhere else.

**Comment by growled** [comment]
![image](https://user-images.githubusercontent.com/77838632/134815552-cec3c0eb-b691-4dab-ac3b-d1cdc0a7eed2.png)

**Comment by joker-119** [comment]
I already intend to re-add this, I have just been too busy to get to it. The reason it's not there now is EXILED itself no longer provides events for commands.

This will be re-added, but no ETA yet.
