### ISSUE TITLE
Remote admin commands don't get logged

### ISSUE THREAD

**Issue by DinoNuggets2** [Exiled-Team/DiscordIntegration#83]
**Describe the bug**
Will not log admin commands to it's own channel

**To Reproduce**
1. Set command: config to it's own channel ID
2. Try sending a test command, for example @test

**Expected behavior**
Expected logs to appear

**Server logs**
https://pastebin.com/8xZqj1eW

**EXILED Version ("latest" is not a version):**
EXILED 5.0.0-beta.5

**Results of `show plugins` command in console:**
Enabled plugins: 30
                           Disabled plugins: 3
                           
                           Exiled.Events:
                                - Author: Exiled Team
                                - Version: 5.0.0.0
                                - Required Exiled Version: 5.0.0.0
                                - Prefix: exiled_events
                                - Priority: Highest
                           CedMod:
                                - Author: ced777ric#8321
                                - Version: 3.0.3
                                - Required Exiled Version: 5.0.0
                                - Prefix: cm
                                - Priority: Highest
                           Spectator Shooting Range:
                                - Author: rayzer
                                - Version: 2.0.0
                                - Required Exiled Version: 5.0.0
                                - Prefix: spectator_shooting_range
                                - Priority: Higher
                           MapEditorReborn:
                                - Author: Michal78900 (original idea by Killers0992)
                                - Version: 2.0.0
                                - Required Exiled Version: 5.0.0
                                - Prefix: map_editor_reborn
                                - Priority: Medium
                           Exiled.CustomRoles:
                                - Author: Exiled Team
                                - Version: 5.0.0.0
                                - Required Exiled Version: 5.0.0.0
                                - Prefix: exiled_custom_roles
                                - Priority: Medium
                           CustomDoorAccess:
                                - Disabled
                                - Author: Faety
                                - Version: 1.4.0
                                - Required Exiled Version: 3.7.2
                                - Prefix: cda
                                - Priority: Medium
                           WaitAndChillReborn:
                                - Author: Michal78900
                                - Version: 5.0.0
                                - Required Exiled Version: 5.0.0
                                - Prefix: wait_and_chill_reborn
                                - Priority: Medium
                           AnimatedServerTitle:
                                - Author: Killers0992
                                - Version: 1.0.1
                                - Required Exiled Version: 5.0.0.0
                                - Prefix: animatedservertitle
                                - Priority: Medium
                           Scp035:
                                - Author: Joker119
                                - Version: 4.0.3
                                - Required Exiled Version: 5.0.0
                                - Prefix: Scp035
                                - Priority: Medium
                           Common Utilities:
                                - Author: Galaxy119
                                - Version: 6.0.0.0
                                - Required Exiled Version: 5.0.0
                                - Prefix: CommonUtilities
                                - Priority: Medium
                           RespawnTimer:
                                - Author: Michal78900
                                - Version: 3.1.0
                                - Required Exiled Version: 5.0.0
                                - Prefix: respawn_timer
                                - Priority: Medium
                           LeftHandedPlayers:
                                - Author: TemmieGamerGuy
                                - Version: 1.0.1
                                - Required Exiled Version: 3.0.0
                                - Prefix: left_handed_players
                                - Priority: Medium
                           Exiled.Updater:
                                - Author: Exiled.Updater
                                - Version: 3.1.1.0
                                - Required Exiled Version: 5.0.0.0
                                - Prefix: exiled_updater
                                - Priority: Medium
                           Exiled.CustomItems:
                                - Author: Exiled Team
                                - Version: 5.0.0.0
                                - Required Exiled Version: 5.0.0.0
                                - Prefix: exiled_custom_items
                                - Priority: Medium
                           Admin Tools:
                                - Author: Originally by Galaxy119. Modifications by KoukoCocoa & Thomasjosif
                                - Version: 5.0.0.0
                                - Required Exiled Version: 5.0.0
                                - Prefix: AT
                                - Priority: Medium
                           CedMod-Events:
                                - Author: ced777ric#8321
                                - Version: 3.0.3
                                - Required Exiled Version: 5.0.0
                                - Prefix: cm_events
                                - Priority: Medium
                           CedMod-WebAPI:
                                - Author: ced777ric#8321
                                - Version: 3.0.3
                                - Required Exiled Version: 5.0.0
                                - Prefix: cm_WAPI
                                - Priority: Medium
                           CustomWarheadColor:
                                - Author: SoraCént
                                - Version: 0.1.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: custom_warhead_color
                                - Priority: Medium
                           SCP-575:
                                - Disabled
                                - Author: Joker119
                                - Version: 4.0.0
                                - Required Exiled Version: 5.0.0
                                - Prefix: 575
                                - Priority: Medium
                           NukeLock:
                                - Author: Marco15453
                                - Version: 1.9.0
                                - Required Exiled Version: 5.0.0
                                - Prefix: nuke_lock
                                - Priority: Medium
                           Exiled.Permissions:
                                - Author: Exiled Team
                                - Version: 5.0.0.0
                                - Required Exiled Version: 5.0.0.0
                                - Prefix: exiled_permissions
                                - Priority: Medium
                           Battery:
                                - Author: ErrorSaid
                                - Version: 1.0.0.0
                                - Required Exiled Version: 5.0.0
                                - Prefix: RadioBattery
                                - Priority: Medium
                           CustomItems:
                                - Author: Exiled Team
                                - Version: 6.0.1.0
                                - Required Exiled Version: 5.0.0
                                - Prefix: custom_items
                                - Priority: Medium
                           SummonRespawnVehicles:
                                - Author: 
                                - Version: 1.0.0.0
                                - Required Exiled Version: 5.0.0.0
                                - Prefix: summon_respawn_vehicles
                                - Priority: Medium
                           Exiled.CreditTags:
                                - Author: Babyboucher20 & iRebbok & Exiled Team
                                - Version: 5.0.0.0
                                - Required Exiled Version: 5.0.0.0
                                - Prefix: exiled_credits
                                - Priority: Medium
                           UIURescueSquad:
                                - Author: JesusQC, Michal78900, maintained by Marco15453
                                - Version: 3.2.0
                                - Required Exiled Version: 5.0.0
                                - Prefix: UIURescueSquad
                                - Priority: Medium
                           LogArchiver:
                                - Author: Galaxy119
                                - Version: 1.0.0
                                - Required Exiled Version: 2.1.18
                                - Prefix: LogArchiver
                                - Priority: Medium
                           LightsRE:
                                - Disabled
                                - Author: Beryl - (Contributors: BuildBoy12)
                                - Version: 4.0.1
                                - Required Exiled Version: 3.0.0
                                - Prefix: lights
                                - Priority: Medium
                           SCP1162:
                                - Author: xRoier
                                - Version: 4.0.0
                                - Required Exiled Version: 4.0.0
                                - Prefix: scp1162
                                - Priority: Medium
                           DiscordIntegration:
                                - Author: Exiled Team
                                - Version: 5.0.4.0
                                - Required Exiled Version: 5.0.0
                                - Prefix: discord_integration
                                - Priority: Medium
                           SupplyDrop:
                                - Author: Wafel, KadeDev, JesusQC
                                - Version: 3.3.0
                                - Required Exiled Version: 5.0.0
                                - Prefix: SD
                                - Priority: Medium
                           Stalky106:
                                - Author: RogerFK && Raul125
                                - Version: 3.3.1
                                - Required Exiled Version: 5.0.0
                                - Prefix: ST106
                                - Priority: Medium
                           Smelly096:
                                - Author: x3rt
                                - Version: 1.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: smelly096
                                - Priority: Lowest

**Additional context**

**Comment by joker-119** [comment]
Wrong logs, I need LocalAdmin server logs, not the round logs, those are useless in every way.
I'll also need the bots logs

**Comment by DinoNuggets2** [comment]
Heres LA logs - https://pastebin.com/QLTmVcnR

DI bot logs were too big for Pastebin, I can send the direct link, or just make it smaller if needed
