### ISSUE TITLE
When round starts the bot becames not responsive

### ISSUE THREAD

**Issue by Lazyas** [Exiled-Team/DiscordIntegration#86]
when round starts the bot just became not responsible,it sees my commands but not answering me and it's not posting logs etc.
but the bot or the game server is not giving me any errors until game ends. When game ends its become responsive again and just says this thing:

```[2022-04-19 15:01:28.708 +00:00] [ERROR] [DiscordIntegration] [NET] An error has occurred while sending data: Unable to write data to the transport connection: The socket has been shut down.```

**Comment by joker-119** [comment]
Make sure the port is open in the firewall, and that nothing else is trying to use the same tcp port number. 
Also make sure all of the node modules are installed correctly with npm install, this is a configuration issue, either with the system, or running the bot in an unsupported fashion (like running the bot and SCP server on seperate machines or with outdated nodejs)
