### ISSUE TITLE
[BUG] Server log is spammed with System.String[]

### ISSUE THREAD

**Issue by Zenlet** [Exiled-Team/DiscordIntegration#93]
**Describe the bug**
The bot spams server logs with lines upon lines of System.String[]

**To Reproduce**
Unsure on how to reproduce

**Expected behavior**
For any gameplay related action to show in the logs

**EXILED Version ("latest" is not a version):**
5.1.1

**Additional context**
![RyLM7vnLH0](https://user-images.githubusercontent.com/62112167/172232086-1b2d3dad-300e-43ee-ab1b-ce4b2111d7df.png)

**Comment by joker-119** [comment]
Out of curiosity, does this only seem to happen when **a lot** of things are happening on the server in a short timeframe?
Like, if there's only one person running around opening doors and interacting with items, logs are fine, but if there's 20 people it does this?

**Comment by Zenlet** [comment]
No idea what causes it

**Comment by joker-119** [comment]
Try updating the bot to the newest release (1.3.1) and see if the issue persists.

**Comment by Zenlet** [comment]
Seems to have fixed it, thanks :)
