### ISSUE TITLE
[Enhancement] Make server number unimportant parameter

### ISSUE THREAD

**Issue by iojforever** [Exiled-Team/DiscordIntegration#98]
**What i mean is:**
To send a command, you need to write server number. Its kinda useless for people with only one server, so, what about make that parameter additional, and by default use server 1? Or maybe use server parameter after command? What do YOU think?
**I dunno how that really works, so prob that idea is trashy, still worthy to tell.**

**Comment by joker-119** [comment]
This is already planned for the next big update, which will remove the need for multiple bot tokens.
